from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
      migrations.CreateModel(name='Category',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=80)),('slug',models.SlugField(max_length=90,unique=True))],options={'ordering':['name']}),
      migrations.CreateModel(name='Product',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=160)),('description',models.TextField()),('price',models.DecimalField(decimal_places=2,max_digits=10)),('stock',models.PositiveIntegerField(default=0)),('image',models.ImageField(blank=True,null=True,upload_to='products/')),('is_active',models.BooleanField(default=True)),('date_created',models.DateTimeField(auto_now_add=True)),('category',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='products',to='store.category'))],options={'ordering':['-date_created']}),
      migrations.CreateModel(name='Order',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('customer_name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254)),('phone',models.CharField(max_length=16)),('address',models.CharField(max_length=255)),('city',models.CharField(max_length=100)),('shipping_method',models.CharField(choices=[('standard','Standard · 3–5 days'),('express','Express · 1–2 days')],default='standard',max_length=20)),('payment_method',models.CharField(choices=[('cod','Cash on Delivery'),('later','Pay Later')],default='cod',max_length=20)),('total',models.DecimalField(decimal_places=2,default=0,max_digits=12)),('status',models.CharField(choices=[('pending','Pending'),('processing','Processing'),('completed','Completed')],default='pending',max_length=20)),('date_created',models.DateTimeField(auto_now_add=True))]),
      migrations.CreateModel(name='OrderItem',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('quantity',models.PositiveIntegerField()),('unit_price',models.DecimalField(decimal_places=2,max_digits=10)),('order',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='items',to='store.order')),('product',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='store.product'))])
    ]
